######################################################################
# Automatically generated by qmake (2.00a) Mi Jul 26 19:12:42 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

QT += sql
CONFIG += qt release warn_on

# Input
HEADERS += fmMain.h
FORMS += fmMain.ui
SOURCES += fmMain.cpp main.cpp
